<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20181227172049 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE absences DROP FOREIGN KEY absences_etudiant_idetudiant_foreign');
        $this->addSql('ALTER TABLE decision_semestres DROP FOREIGN KEY decision_semestres_etudiant_idetudiant_foreign');
        $this->addSql('ALTER TABLE decision_u_es DROP FOREIGN KEY decision_u_es_etudiant_idetudiant_foreign');
        $this->addSql('ALTER TABLE diplomes DROP FOREIGN KEY diplomes_etudiant_idetudiant_foreign');
        $this->addSql('ALTER TABLE notes DROP FOREIGN KEY notes_etudiant_idetudiant_foreign');
        $this->addSql('ALTER TABLE photos DROP FOREIGN KEY photos_etudiant_idetudiant_foreign');
        $this->addSql('ALTER TABLE etudiants DROP FOREIGN KEY etudiants_formation_idformation_foreign');
        $this->addSql('ALTER TABLE notes DROP FOREIGN KEY notes_matiere_idmatiere_foreign');
        $this->addSql('ALTER TABLE decision_semestres DROP FOREIGN KEY decision_semestres_semestre_idsemestre_foreign');
        $this->addSql('ALTER TABLE etudiants DROP FOREIGN KEY etudiants_semestre_idsemestre_foreign');
        $this->addSql('ALTER TABLE u_es DROP FOREIGN KEY u_es_semestre_idsemestre_foreign');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D13FE97E50');
        $this->addSql('ALTER TABLE absences DROP FOREIGN KEY absences_ue_idue_foreign');
        $this->addSql('ALTER TABLE decision_u_es DROP FOREIGN KEY decision_u_es_ue_idue_foreign');
        $this->addSql('ALTER TABLE matieres DROP FOREIGN KEY matieres_ue_idue_foreign');
        $this->addSql('DROP TABLE absences');
        $this->addSql('DROP TABLE decision_semestres');
        $this->addSql('DROP TABLE decision_u_es');
        $this->addSql('DROP TABLE diplomes');
        $this->addSql('DROP TABLE etudiants');
        $this->addSql('DROP TABLE formations');
        $this->addSql('DROP TABLE matieres');
        $this->addSql('DROP TABLE migrations');
        $this->addSql('DROP TABLE notes');
        $this->addSql('DROP TABLE password_resets');
        $this->addSql('DROP TABLE photos');
        $this->addSql('DROP TABLE semestres');
        $this->addSql('DROP TABLE type_transaction');
        $this->addSql('DROP TABLE u_es');
        $this->addSql('DROP TABLE users');
        $this->addSql('ALTER TABLE categorie MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE categorie DROP FOREIGN KEY FK_497DD634F520CF5A');
        $this->addSql('DROP INDEX IDX_497DD634F520CF5A ON categorie');
        $this->addSql('ALTER TABLE categorie DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE categorie ADD nomCategorie VARCHAR(45) DEFAULT NULL, ADD descriptionCategorie TEXT DEFAULT NULL, DROP objet_id, DROP nom_categorie, DROP description_categorie, CHANGE id idcategorie INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE categorie ADD PRIMARY KEY (idcategorie)');
        $this->addSql('ALTER TABLE conversation MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E925321056');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E95F876A71');
        $this->addSql('DROP INDEX UNIQ_8A8E26E925321056 ON conversation');
        $this->addSql('DROP INDEX UNIQ_8A8E26E95F876A71 ON conversation');
        $this->addSql('ALTER TABLE conversation DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE conversation ADD idEnvoyeur INT DEFAULT NULL, ADD idObjetConcerne INT DEFAULT NULL, DROP id_envoyeur_id, DROP id_objet_concerne_id, CHANGE date date TEXT DEFAULT NULL, CHANGE id idConversation INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9772196B FOREIGN KEY (idEnvoyeur) REFERENCES user (iduser)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9AB2B8645 FOREIGN KEY (idObjetConcerne) REFERENCES objet (idobjet)');
        $this->addSql('CREATE INDEX idObjetConcerne_idx ON conversation (idObjetConcerne)');
        $this->addSql('CREATE INDEX idEnvoyeur_idx ON conversation (idEnvoyeur)');
        $this->addSql('ALTER TABLE conversation ADD PRIMARY KEY (idConversation)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5B597FD62 FOREIGN KEY (idCategorie) REFERENCES categorie (idcategorie)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5E339724C FOREIGN KEY (idTypeTransaction) REFERENCES typetransaction (idtypetransaction)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (iduser)');
        $this->addSql('ALTER TABLE message MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F79F37AE5');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FE0F2C01E');
        $this->addSql('DROP INDEX IDX_B6BD307FE0F2C01E ON message');
        $this->addSql('DROP INDEX IDX_B6BD307F79F37AE5 ON message');
        $this->addSql('ALTER TABLE message DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE message ADD Conversation_idConversation INT DEFAULT NULL, ADD User_idUser INT DEFAULT NULL, DROP id_conversation_id, DROP id_user_id, CHANGE id idMessage INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F2B91B642 FOREIGN KEY (Conversation_idConversation) REFERENCES conversation (idconversation)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F1DA01C3D FOREIGN KEY (User_idUser) REFERENCES user (iduser)');
        $this->addSql('CREATE INDEX fk_Conversation_has_User_User1_idx ON message (User_idUser)');
        $this->addSql('CREATE INDEX fk_Conversation_has_User_Conversation1_idx ON message (Conversation_idConversation)');
        $this->addSql('ALTER TABLE message ADD PRIMARY KEY (idMessage)');
        $this->addSql('ALTER TABLE objet MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE objet DROP FOREIGN KEY FK_46CD4C389F9BCDC2');
        $this->addSql('DROP INDEX IDX_46CD4C389F9BCDC2 ON objet');
        $this->addSql('ALTER TABLE objet DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE objet ADD nomObjet VARCHAR(45) DEFAULT NULL, ADD idCategorie INT DEFAULT NULL, ADD idTransaction INT DEFAULT NULL, ADD idProprietaire INT DEFAULT NULL, DROP id_proprietaire_id, DROP nom_objet, CHANGE disponible Disponible TINYINT(1) DEFAULT NULL, CHANGE id idObjet INT AUTO_INCREMENT NOT NULL, CHANGE description_objet descriptionObjet TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE objet ADD CONSTRAINT FK_46CD4C38B597FD62 FOREIGN KEY (idCategorie) REFERENCES categorie (idcategorie)');
        $this->addSql('ALTER TABLE objet ADD CONSTRAINT FK_46CD4C38326AFAA9 FOREIGN KEY (idTransaction) REFERENCES transaction (idtransaction)');
        $this->addSql('ALTER TABLE objet ADD CONSTRAINT FK_46CD4C38377D3D27 FOREIGN KEY (idProprietaire) REFERENCES user (iduser)');
        $this->addSql('CREATE INDEX idTransaction_idx ON objet (idTransaction)');
        $this->addSql('CREATE INDEX idUser_idx ON objet (idProprietaire)');
        $this->addSql('CREATE INDEX idCategorie_idx ON objet (idCategorie)');
        $this->addSql('ALTER TABLE objet ADD PRIMARY KEY (idObjet)');
        $this->addSql('ALTER TABLE photo MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE photo DROP FOREIGN KEY FK_14B78418A5FB23CF');
        $this->addSql('DROP INDEX IDX_14B78418A5FB23CF ON photo');
        $this->addSql('ALTER TABLE photo DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE photo ADD cheminPhoto TEXT DEFAULT NULL, DROP chemin_photo, CHANGE id idPhoto INT AUTO_INCREMENT NOT NULL, CHANGE image_principale imagePrincipale TINYINT(1) DEFAULT NULL, CHANGE id_objet_id Objet_idObjet INT DEFAULT NULL');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418397952EB FOREIGN KEY (Objet_idObjet) REFERENCES objet (idobjet)');
        $this->addSql('CREATE INDEX fk_Photo_Objet1_idx ON photo (Objet_idObjet)');
        $this->addSql('ALTER TABLE photo ADD PRIMARY KEY (idPhoto)');
        $this->addSql('ALTER TABLE profil MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE profil DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE profil ADD nomProfil VARCHAR(45) DEFAULT NULL, DROP nom_profil, CHANGE id idProfil INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE profil ADD PRIMARY KEY (idProfil)');
        $this->addSql('ALTER TABLE transaction MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D157A29CC5');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1A5FB23CF');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1E45DFA4C');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1F520CF5A');
        $this->addSql('DROP INDEX IDX_723705D1F520CF5A ON transaction');
        $this->addSql('DROP INDEX UNIQ_723705D13FE97E50 ON transaction');
        $this->addSql('DROP INDEX UNIQ_723705D157A29CC5 ON transaction');
        $this->addSql('DROP INDEX UNIQ_723705D1E45DFA4C ON transaction');
        $this->addSql('DROP INDEX IDX_723705D1A5FB23CF ON transaction');
        $this->addSql('ALTER TABLE transaction DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE transaction ADD transactionRealisée TINYINT(1) DEFAULT NULL, ADD idObjet INT DEFAULT NULL, ADD idTypeTranasaction INT DEFAULT NULL, ADD idUserDemandeur INT DEFAULT NULL, ADD idUserOffrant INT DEFAULT NULL, DROP id_objet_id, DROP id_user_offrant_id, DROP id_user_demandeur_id, DROP id_type_transaction_id, DROP objet_id, DROP transaction_realisee, CHANGE id idtransaction INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D151090F25 FOREIGN KEY (idObjet) REFERENCES objet (idobjet)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1E9B30482 FOREIGN KEY (idTypeTranasaction) REFERENCES typetransaction (idtypetransaction)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1E005D9FE FOREIGN KEY (idUserDemandeur) REFERENCES user (iduser)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D11FF98D8E FOREIGN KEY (idUserOffrant) REFERENCES user (iduser)');
        $this->addSql('CREATE INDEX idTypeTransaction_idx ON transaction (idTypeTranasaction)');
        $this->addSql('CREATE INDEX idUserDemandeur_idx ON transaction (idUserDemandeur)');
        $this->addSql('CREATE INDEX idUserOffrant_idx ON transaction (idUserOffrant)');
        $this->addSql('CREATE INDEX idObjet_idx ON transaction (idObjet)');
        $this->addSql('ALTER TABLE transaction ADD PRIMARY KEY (idtransaction)');
        $this->addSql('ALTER TABLE user MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649A76B6C5F');
        $this->addSql('DROP INDEX UNIQ_8D93D649A76B6C5F ON user');
        $this->addSql('ALTER TABLE user DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE user ADD nomUser VARCHAR(45) NOT NULL, ADD prenomPersonne VARCHAR(45) NOT NULL, ADD emailUser VARCHAR(45) NOT NULL, ADD passwordUser VARCHAR(45) NOT NULL, ADD idProfil INT DEFAULT NULL, DROP id_profil_id, DROP nom_user, DROP prenom_user, DROP email_user, DROP password_user, CHANGE pseudo pseudo VARCHAR(45) DEFAULT NULL, CHANGE avatar avatar VARCHAR(45) DEFAULT NULL, CHANGE id idUser INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64985C71A0D FOREIGN KEY (idProfil) REFERENCES profil (idprofil)');
        $this->addSql('CREATE INDEX idProfil_idx ON user (idProfil)');
        $this->addSql('ALTER TABLE user ADD PRIMARY KEY (idUser)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE absences (idAbscence INT UNSIGNED AUTO_INCREMENT NOT NULL, heures INT NOT NULL, Etudiant_idEtudiant INT UNSIGNED NOT NULL, UE_idUE INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX absences_ue_idue_foreign (UE_idUE), INDEX absences_etudiant_idetudiant_foreign (Etudiant_idEtudiant), PRIMARY KEY(idAbscence)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE decision_semestres (idDecisionSemestre INT UNSIGNED AUTO_INCREMENT NOT NULL, decision VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, Etudiant_idEtudiant INT UNSIGNED NOT NULL, Semestre_idSemestre INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX decision_semestres_semestre_idsemestre_foreign (Semestre_idSemestre), INDEX decision_semestres_etudiant_idetudiant_foreign (Etudiant_idEtudiant), PRIMARY KEY(idDecisionSemestre)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE decision_u_es (idDecisionUE INT UNSIGNED AUTO_INCREMENT NOT NULL, decision VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, Etudiant_idEtudiant INT UNSIGNED NOT NULL, UE_idUE INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX decision_u_es_ue_idue_foreign (UE_idUE), INDEX decision_u_es_etudiant_idetudiant_foreign (Etudiant_idEtudiant), PRIMARY KEY(idDecisionUE)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE diplomes (idDiplome INT UNSIGNED AUTO_INCREMENT NOT NULL, nom VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, debut DATE NOT NULL, fin DATE NOT NULL, Etudiant_idEtudiant INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX diplomes_etudiant_idetudiant_foreign (Etudiant_idEtudiant), PRIMARY KEY(idDiplome)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE etudiants (idEtudiant INT UNSIGNED AUTO_INCREMENT NOT NULL, nom VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, prenom VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, numEtu VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, groupe VARCHAR(5) NOT NULL COLLATE utf8mb4_unicode_ci, Formation_idFormation INT UNSIGNED NOT NULL, Semestre_idSemestre INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX etudiants_semestre_idsemestre_foreign (Semestre_idSemestre), INDEX etudiants_formation_idformation_foreign (Formation_idFormation), PRIMARY KEY(idEtudiant)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE formations (idFormation INT UNSIGNED AUTO_INCREMENT NOT NULL, nom VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(idFormation)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE matieres (idMatiere INT UNSIGNED AUTO_INCREMENT NOT NULL, nom VARCHAR(150) NOT NULL COLLATE utf8mb4_unicode_ci, ref TEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, abreviation CHAR(10) NOT NULL COLLATE utf8mb4_unicode_ci, coefficient NUMERIC(8, 2) NOT NULL, UE_idUE INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX matieres_ue_idue_foreign (UE_idUE), PRIMARY KEY(idMatiere)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE migrations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, migration VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, batch INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notes (idNote INT UNSIGNED AUTO_INCREMENT NOT NULL, note NUMERIC(4, 2) NOT NULL, Etudiant_idEtudiant INT UNSIGNED NOT NULL, Matiere_idMatiere INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX notes_matiere_idmatiere_foreign (Matiere_idMatiere), INDEX notes_etudiant_idetudiant_foreign (Etudiant_idEtudiant), PRIMARY KEY(idNote)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE password_resets (email VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, token VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, created_at DATETIME DEFAULT NULL, INDEX password_resets_email_index (email)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE photos (idPhoto INT UNSIGNED AUTO_INCREMENT NOT NULL, chemin VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, image VARCHAR(255) NOT NULL, Etudiant_idEtudiant INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX photos_etudiant_idetudiant_foreign (Etudiant_idEtudiant), PRIMARY KEY(idPhoto)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE semestres (idSemestre INT UNSIGNED AUTO_INCREMENT NOT NULL, nom VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, debut DATE NOT NULL, fin DATE NOT NULL, Formation_idFormation INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(idSemestre)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE type_transaction (id INT AUTO_INCREMENT NOT NULL, nom_transaction VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, date_debut_transaction DATE NOT NULL, date_fin_transaction DATE DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE u_es (idUE INT UNSIGNED AUTO_INCREMENT NOT NULL, nomUE VARCHAR(45) NOT NULL COLLATE utf8mb4_unicode_ci, debut DATE NOT NULL, fin DATE NOT NULL, Semestre_idSemestre INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX u_es_semestre_idsemestre_foreign (Semestre_idSemestre), PRIMARY KEY(idUE)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, email VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, email_verified_at DATETIME DEFAULT NULL, password VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, remember_token VARCHAR(100) DEFAULT NULL COLLATE utf8mb4_unicode_ci, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX users_email_unique (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT absences_etudiant_idetudiant_foreign FOREIGN KEY (Etudiant_idEtudiant) REFERENCES etudiants (idetudiant) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT absences_ue_idue_foreign FOREIGN KEY (UE_idUE) REFERENCES u_es (idue) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE decision_semestres ADD CONSTRAINT decision_semestres_etudiant_idetudiant_foreign FOREIGN KEY (Etudiant_idEtudiant) REFERENCES etudiants (idetudiant) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE decision_semestres ADD CONSTRAINT decision_semestres_semestre_idsemestre_foreign FOREIGN KEY (Semestre_idSemestre) REFERENCES semestres (idsemestre) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE decision_u_es ADD CONSTRAINT decision_u_es_etudiant_idetudiant_foreign FOREIGN KEY (Etudiant_idEtudiant) REFERENCES etudiants (idetudiant) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE decision_u_es ADD CONSTRAINT decision_u_es_ue_idue_foreign FOREIGN KEY (UE_idUE) REFERENCES u_es (idue) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE diplomes ADD CONSTRAINT diplomes_etudiant_idetudiant_foreign FOREIGN KEY (Etudiant_idEtudiant) REFERENCES etudiants (idetudiant) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE etudiants ADD CONSTRAINT etudiants_formation_idformation_foreign FOREIGN KEY (Formation_idFormation) REFERENCES formations (idformation) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE etudiants ADD CONSTRAINT etudiants_semestre_idsemestre_foreign FOREIGN KEY (Semestre_idSemestre) REFERENCES semestres (idsemestre) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE matieres ADD CONSTRAINT matieres_ue_idue_foreign FOREIGN KEY (UE_idUE) REFERENCES u_es (idue) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE notes ADD CONSTRAINT notes_etudiant_idetudiant_foreign FOREIGN KEY (Etudiant_idEtudiant) REFERENCES etudiants (idetudiant) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE notes ADD CONSTRAINT notes_matiere_idmatiere_foreign FOREIGN KEY (Matiere_idMatiere) REFERENCES matieres (idmatiere) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE photos ADD CONSTRAINT photos_etudiant_idetudiant_foreign FOREIGN KEY (Etudiant_idEtudiant) REFERENCES etudiants (idetudiant) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE u_es ADD CONSTRAINT u_es_semestre_idsemestre_foreign FOREIGN KEY (Semestre_idSemestre) REFERENCES semestres (idsemestre) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE categorie MODIFY idcategorie INT NOT NULL');
        $this->addSql('ALTER TABLE categorie DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE categorie ADD objet_id INT NOT NULL, ADD nom_categorie VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, ADD description_categorie VARCHAR(10000) DEFAULT NULL COLLATE utf8mb4_unicode_ci, DROP nomCategorie, DROP descriptionCategorie, CHANGE idcategorie id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE categorie ADD CONSTRAINT FK_497DD634F520CF5A FOREIGN KEY (objet_id) REFERENCES objet (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_497DD634F520CF5A ON categorie (objet_id)');
        $this->addSql('ALTER TABLE categorie ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE conversation MODIFY idConversation INT NOT NULL');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E9772196B');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E9AB2B8645');
        $this->addSql('DROP INDEX idObjetConcerne_idx ON conversation');
        $this->addSql('DROP INDEX idEnvoyeur_idx ON conversation');
        $this->addSql('ALTER TABLE conversation DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE conversation ADD id_envoyeur_id INT DEFAULT NULL, ADD id_objet_concerne_id INT DEFAULT NULL, DROP idEnvoyeur, DROP idObjetConcerne, CHANGE date date LONGTEXT NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE idconversation id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E925321056 FOREIGN KEY (id_objet_concerne_id) REFERENCES objet (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E95F876A71 FOREIGN KEY (id_envoyeur_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A8E26E925321056 ON conversation (id_objet_concerne_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A8E26E95F876A71 ON conversation (id_envoyeur_id)');
        $this->addSql('ALTER TABLE conversation ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE demande DROP FOREIGN KEY FK_2694D7A5B597FD62');
        $this->addSql('ALTER TABLE demande DROP FOREIGN KEY FK_2694D7A5E339724C');
        $this->addSql('ALTER TABLE demande DROP FOREIGN KEY FK_2694D7A5FE6E88D7');
        $this->addSql('ALTER TABLE message MODIFY idMessage INT NOT NULL');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F2B91B642');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F1DA01C3D');
        $this->addSql('DROP INDEX fk_Conversation_has_User_User1_idx ON message');
        $this->addSql('DROP INDEX fk_Conversation_has_User_Conversation1_idx ON message');
        $this->addSql('ALTER TABLE message DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE message ADD id_conversation_id INT NOT NULL, ADD id_user_id INT NOT NULL, DROP Conversation_idConversation, DROP User_idUser, CHANGE idmessage id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE0F2C01E FOREIGN KEY (id_conversation_id) REFERENCES conversation (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_B6BD307FE0F2C01E ON message (id_conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F79F37AE5 ON message (id_user_id)');
        $this->addSql('ALTER TABLE message ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE objet MODIFY idObjet INT NOT NULL');
        $this->addSql('ALTER TABLE objet DROP FOREIGN KEY FK_46CD4C38B597FD62');
        $this->addSql('ALTER TABLE objet DROP FOREIGN KEY FK_46CD4C38326AFAA9');
        $this->addSql('ALTER TABLE objet DROP FOREIGN KEY FK_46CD4C38377D3D27');
        $this->addSql('DROP INDEX idTransaction_idx ON objet');
        $this->addSql('DROP INDEX idUser_idx ON objet');
        $this->addSql('DROP INDEX idCategorie_idx ON objet');
        $this->addSql('ALTER TABLE objet DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE objet ADD id_proprietaire_id INT NOT NULL, ADD nom_objet VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, DROP nomObjet, DROP idCategorie, DROP idTransaction, DROP idProprietaire, CHANGE Disponible disponible TINYINT(1) NOT NULL, CHANGE idobjet id INT AUTO_INCREMENT NOT NULL, CHANGE descriptionobjet description_objet LONGTEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE objet ADD CONSTRAINT FK_46CD4C389F9BCDC2 FOREIGN KEY (id_proprietaire_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_46CD4C389F9BCDC2 ON objet (id_proprietaire_id)');
        $this->addSql('ALTER TABLE objet ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE photo MODIFY idPhoto INT NOT NULL');
        $this->addSql('ALTER TABLE photo DROP FOREIGN KEY FK_14B78418397952EB');
        $this->addSql('DROP INDEX fk_Photo_Objet1_idx ON photo');
        $this->addSql('ALTER TABLE photo DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE photo ADD chemin_photo LONGTEXT NOT NULL COLLATE utf8mb4_unicode_ci, DROP cheminPhoto, CHANGE idphoto id INT AUTO_INCREMENT NOT NULL, CHANGE objet_idobjet id_objet_id INT DEFAULT NULL, CHANGE imageprincipale image_principale TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418A5FB23CF FOREIGN KEY (id_objet_id) REFERENCES objet (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_14B78418A5FB23CF ON photo (id_objet_id)');
        $this->addSql('ALTER TABLE photo ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE profil MODIFY idProfil INT NOT NULL');
        $this->addSql('ALTER TABLE profil DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE profil ADD nom_profil VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, DROP nomProfil, CHANGE idprofil id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE profil ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE transaction MODIFY idtransaction INT NOT NULL');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D151090F25');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1E9B30482');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1E005D9FE');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D11FF98D8E');
        $this->addSql('DROP INDEX idTypeTransaction_idx ON transaction');
        $this->addSql('DROP INDEX idUserDemandeur_idx ON transaction');
        $this->addSql('DROP INDEX idUserOffrant_idx ON transaction');
        $this->addSql('DROP INDEX idObjet_idx ON transaction');
        $this->addSql('ALTER TABLE transaction DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE transaction ADD id_objet_id INT DEFAULT NULL, ADD id_user_offrant_id INT NOT NULL, ADD id_user_demandeur_id INT NOT NULL, ADD id_type_transaction_id INT NOT NULL, ADD objet_id INT DEFAULT NULL, ADD transaction_realisee TINYINT(1) NOT NULL, DROP transactionRealisée, DROP idObjet, DROP idTypeTranasaction, DROP idUserDemandeur, DROP idUserOffrant, CHANGE idtransaction id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D13FE97E50 FOREIGN KEY (id_type_transaction_id) REFERENCES type_transaction (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D157A29CC5 FOREIGN KEY (id_user_offrant_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A5FB23CF FOREIGN KEY (id_objet_id) REFERENCES objet (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1E45DFA4C FOREIGN KEY (id_user_demandeur_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1F520CF5A FOREIGN KEY (objet_id) REFERENCES objet (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_723705D1F520CF5A ON transaction (objet_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_723705D13FE97E50 ON transaction (id_type_transaction_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_723705D157A29CC5 ON transaction (id_user_offrant_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_723705D1E45DFA4C ON transaction (id_user_demandeur_id)');
        $this->addSql('CREATE INDEX IDX_723705D1A5FB23CF ON transaction (id_objet_id)');
        $this->addSql('ALTER TABLE transaction ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE user MODIFY idUser INT NOT NULL');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64985C71A0D');
        $this->addSql('DROP INDEX idProfil_idx ON user');
        $this->addSql('ALTER TABLE user DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE user ADD id_profil_id INT NOT NULL, ADD nom_user VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, ADD prenom_user VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, ADD email_user VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, ADD password_user VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, DROP nomUser, DROP prenomPersonne, DROP emailUser, DROP passwordUser, DROP idProfil, CHANGE pseudo pseudo VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, CHANGE avatar avatar VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, CHANGE iduser id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649A76B6C5F FOREIGN KEY (id_profil_id) REFERENCES profil (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649A76B6C5F ON user (id_profil_id)');
        $this->addSql('ALTER TABLE user ADD PRIMARY KEY (id)');
    }
}
